### ISSUE TITLE
UserId and JobId

### ISSUE THREAD

**Issue by raymondgitonga** [smileidentity/smile-identity-core-java#13]
Hi Team
Am trying to implement your library, i don't seem to know what parameters to use exactly when building partner parameters.

`var partnerParameters:PartnerParameters = PartnerParameters(userId, jobId,  5)`

What do i pass as userId and jobId. Am using ID verification

**Comment by beaglebets** [comment]
The `userId` and `jobId` parameters should be strings containing unique identifiers. We recommend using UUIDs, although you may also wish to use the user id associated with a user in your database.
